### ISSUE TITLE
error: reference to 'move' is ambiguous

### ISSUE THREAD

**Issue by ryandesign** [logological/cheops#1]
Buliding cheops 1.2 fails on OS X 10.11 with the error:

    error: reference to 'move' is ambiguous

It seems `move` might be a reserved word under libc++. I don't see this problem if I build with libstdc++ instead, but I'd rather not do that. I can also avoid the problem if I rename all occurrences of `move` to something else. I don't know enough about C++ to know if there is an alternative that lets you keep using the name `move` by using namespaces or something.

**Comment by ryandesign** [comment]
> I can also avoid the problem if I rename all occurrences of `move` to something else.

This is what I did in MacPorts:

https://github.com/macports/macports-ports/blob/master/games/cheops/files/libc%2B%2B.patch

**Comment by logological** [comment]
CHEOPS was written in 1998 and hasn't had any major changes since then.  However, it looks like C++11 introduced some `move` functions in the `std` namespace, and CHEOPS's `stdafx.h` has a `using namespace std;` directive.  Maybe this is causing the name clash.

Easiest way around it might be for me to simply rename the type, as you've done in your patch.

**Comment by logological** [comment]
Should be fixed by Commit d3a5371119ef7798f44f4389bb271bdd8628a295.  @ryandesign, could you please check out the latest version and see if it compiles correctly for you now?
